name: shorts

services:
  rabbitmq:
    image: rabbitmq:3-alpine
    env_file: ./.env
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}

  script-gen:
    build:
      context: .
      dockerfile: ./apps/script-gen/Dockerfile
    env_file: ./.env

  renderer:
    build:
      context: .
      dockerfile: ./apps/renderer/Dockerfile
    depends_on:
      - rabbitmq
    env_file: ./.env
    environment:
      RENDER_OUTPUT: "/app/out"
      RABBITMQ_HOSTNAME: rabbitmq
    volumes:
      - type: bind
        bind:
          create_host_path: true
        source: ${RENDER_OUTPUT}
        target: /app/out
    restart: unless-stopped

  gateway:
    build:
      context: .
      dockerfile: ./apps/gateway/Dockerfile
    depends_on:
      - rabbitmq
    env_file: ./.env
    environment:
      RABBITMQ_HOSTNAME: rabbitmq
      BASE_URL_SCRIPT_GEN: http://script-gen:${SERVER_PORT_SCRIPT_GEN}
    expose:
      - ${SERVER_PORT_GATEWAY}
    ports:
      - ${SERVER_PORT_GATEWAY}:${SERVER_PORT_GATEWAY}
    restart: unless-stopped
