import { env } from "common";

export const GATEWAY_SERVER_PORT = env("GATEWAY_SERVER_PORT");

export const BASE_URL_SCRIPT_GEN = env("BASE_URL_SCRIPT_GEN");

export const RABBITMQ_HOSTNAME = env("RABBITMQ_HOSTNAME");
export const RABBITMQ_USERNAME = env("RABBITMQ_USERNAME");
export const RABBITMQ_PASSWORD = env("RABBITMQ_PASSWORD");

export const GATEWAY_AUTH_USERNAME = env("GATEWAY_AUTH_USERNAME");
export const GATEWAY_AUTH_PASSWORD = env("GATEWAY_AUTH_PASSWORD");
